### ISSUE TITLE
Type declarations causing errors in Storybook

### ISSUE THREAD

**Issue by uuuhs** [NiGhTTraX/ts-monorepo#320]
When I change `packages/components/src/button.tsx` code to below
```tsx
/* eslint-disable no-alert */
import { meaningOfLife } from "@nighttrax/foo";
import React, { FC } from "react";

export const Button: FC = () => (
  <button
    type="button"
    onClick={() => alert(`the meaning if life is ${meaningOfLife}`)}
  >
    Click me
  </button>
);
```
Then I run `pnpm -C apps/storybook run storybook`. This is the error.
```
99% end closing watch compilationWARN Force closed preview build
ModuleBuildError: Module build failed (from ../../node_modules/.pnpm/babel-loader@9.1.3_w2y3gebnpzszwk76tjnxtlgew4/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/marvin/Documents/workspaces/ts-2/packages/components/src/button.tsx: Missing initializer in const declaration. (5:19)

  3 | import React, { FC } from "react";
  4 |
> 5 | export const Button: FC = () => (
    |                    ^
  6 |   <button
  7 |     type="button"
  8 |     onClick={() => alert(`the meaning if life is ${meaningOfLife}`)}
    at constructor (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:348:19)
    at JSXParserMixin.raise (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:3202:19)
    at JSXParserMixin.parseVar (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13212:16)
    at JSXParserMixin.parseVarStatement (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13045:10)
    at JSXParserMixin.parseStatementContent (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12628:23)
    at JSXParserMixin.parseStatementLike (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12533:17)
    at JSXParserMixin.parseStatementListItem (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12513:17)
    at JSXParserMixin.parseExportDeclaration (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13780:17)
    at JSXParserMixin.maybeParseExportDeclaration (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13735:31)
    at JSXParserMixin.parseExport (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13658:29)
    at JSXParserMixin.parseStatementContent (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12660:27)
    at JSXParserMixin.parseStatementLike (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12533:17)
    at JSXParserMixin.parseModuleItem (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12510:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13134:36)
    at JSXParserMixin.parseBlockBody (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:13127:10)
    at JSXParserMixin.parseProgram (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12409:10)
    at JSXParserMixin.parseTopLevel (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:12399:25)
    at JSXParserMixin.parse (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:14295:10)
    at parse (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+parser@7.22.16/node_modules/@babel/parser/lib/index.js:14336:38)
    at parser (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+core@7.22.15/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+core@7.22.15/node_modules/@babel/core/lib/transformation/normalize-file.js:64:37)
    at normalizeFile.next (<anonymous>)
    at run (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+core@7.22.15/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+core@7.22.15/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:261:32)
    at /Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:223:11)
    at /Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:189:28
    at /Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/@babel+core@7.22.15/node_modules/@babel/core/lib/gensync-utils/async.js:68:7
    at /Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:113:33
    at step (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:287:14)
    at /Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:223:11)
    at processResult (/Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/webpack@5.88.2_@swc+core@1.3.83/node_modules/webpack/lib/NormalModule.js:764:19)
    at /Users/marvin/Documents/workspaces/ts-2/node_modules/.pnpm/webpack@5.88.2_@swc+core@1.3.83/node_modules/webpack/lib/NormalModule.js:866:5
```

**Comment by uuuhs** [comment]
Why can't I declare the type? Is this file not involved in the build？

**Comment by NiGhTTraX** [comment]
Hey @uuuhs, thanks for reporting this! It was caused by the Babel config file not having the correct name, which was changed during the Storybook@7 upgrade. 8c75005d7f7e5c6e8773659aa0060c845b41523a fixes this, so try to pull the latest version and check if everything's OK.
